### ISSUE TITLE
undefined local variable or method `locale'

### ISSUE THREAD

**Issue by pezholio** [contentful/contentful_model#113]
Hi,

I'm trying to create content via `contentful_model`. I have a model:

```
class Comment < ContentfulModel::Base
  self.content_type_id = 'comment'  
end
```

And when trying to create a new instance of `Comment` like so:

```
c = Comment.new(name: 'Some Name')
c.save
```

I get the following error:

```
NameError:
       undefined local variable or method `locale' for #<Comment:0x00007ff1cf4a4700>
       Did you mean?  locales
```

Any ideas?

**Comment by pezholio** [comment]
I've got a fuller backtrace here, if it helps:

```
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/contentful_model-1.0.0/lib/contentful_model/manageable.rb:83:in `management_proxy'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/contentful_model-1.0.0/lib/contentful_model/manageable.rb:91:in `fetch_management_entry'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/contentful_model-1.0.0/lib/contentful_model/manageable.rb:96:in `management_entry'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/contentful_model-1.0.0/lib/contentful_model/manageable.rb:21:in `to_management'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/contentful_model-1.0.0/lib/contentful_model/manageable.rb:43:in `save'
(irb):4:in `irb_binding'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/workspace.rb:85:in `eval'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/workspace.rb:85:in `evaluate'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/context.rb:380:in `evaluate'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:491:in `block (2 levels) in eval_input'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:621:in `signal_status'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:488:in `block in eval_input'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `loop'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `catch'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:487:in `eval_input'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:428:in `block in run'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:427:in `catch'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:427:in `run'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/irb.rb:383:in `start'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:64:in `start'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:19:in `start'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands/console/console_command.rb:96:in `perform'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command/base.rb:65:in `perform'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/command.rb:46:in `invoke'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.2.0/lib/rails/commands.rb:18:in `<main>'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `block in require'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:283:in `require'
/Users/stuart/Documents/whatworks-csc/bin/rails:11:in `<main>'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bootsnap-1.3.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:50:in `load'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `block in load'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:249:in `load_dependency'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.2.0/lib/active_support/dependencies.rb:277:in `load'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/stuart/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
-e:1:in `<main>'
Traceback (most recent call last):
        1: from (irb):4
NameError (undefined local variable or method `locale' for #<Comment:0x00007fa3eb6689d8>
Did you mean?  locales)
```

**Comment by dlitvakb** [comment]
Hey @pezholio,

You should be using `Comment.create` instead as shown in the documentation here: https://github.com/contentful/contentful_model#creating-entries

Cheers

**Comment by pezholio** [comment]
Ah ha. Gotcha, thanks for the quick response! 👍
