### ISSUE TITLE
Problem with validations on entry_array

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful_model#84]
Running this migration:

```ruby
class ListItemContentType < ActiveRecord::Migration[5.1]
  include ContentfulModel::Migrations::Migration

  def up
    create_content_type("List Item") do |content_type|
      content_type.field("Bullet Image", :asset_link)
      content_type.field("Title", :symbol)
      content_type.field("Subtitle", :symbol)
      content_type.field("Text", :text)
    end.publish
  end
end
```

and then:

```ruby
class ListContentType < ActiveRecord::Migration[5.1]
  include ContentfulModel::Migrations::Migration

  def up
    create_content_type("List") do |content_type|
      content_type.field("List Items", :entry_array).validations = [
        Contentful::Management::Validation.new.tap do |validation|
          validation.link_content_type = ["listItem"]
        end
      ]
    end.publish
  end
end
```

results in:

```
== 20171120133841 ListContentType: migrating ==================================
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `id' for #<Contentful::Management::UnprocessableEntity:0x00007f86314e6a60>
/Users/nomasprime/Organisations/make_it_cheaper/make_it_cheaper/vendor/ruby/2.4.0/bundler/gems/contentful_model-5b1b938156cb/lib/contentful_model/migrations/content_type.rb:58:in `new?'
/Users/nomasprime/Organisations/make_it_cheaper/make_it_cheaper/vendor/ruby/2.4.0/bundler/gems/contentful_model-5b1b938156cb/lib/contentful_model/migrations/content_type.rb:30:in `publish'
/Users/nomasprime/Organisations/make_it_cheaper/make_it_cheaper/db/migrate/20171120133841_list_content_type.rb:11:in `up'
…
```

Works if you change `entry_array` to `entry_link`.

**Comment by nomasprime** [comment]
@dlitvakb any suggestions would be much appreciated. I'll try and debug in the meantime.

**Comment by nomasprime** [comment]
Turns out with `:asset_array` and `:entry_array` you have to reference `items`:

```ruby
class ListContentType < ActiveRecord::Migration[5.1]
  include ContentfulModel::Migrations::Migration

  def up
    create_content_type("List") do |content_type|
      content_type.field("List Items", :entry_array).items.validations = [
        Contentful::Management::Validation.new.tap do |validation|
          validation.link_content_type = ["listItem"]
        end
      ]
    end.publish
  end
end
```
