### ISSUE TITLE
Marshalling error for key .. can't be referred to

### ISSUE THREAD

**Issue by Frexuz** [contentful/contentful_model#89]
Error
```
=> CMS::District.cached_post('central')

Cache read: cms/en-GB/districts/central/v1
Cache generate: cms/en-GB/districts/central/v1
Cache write: cms/en-GB/districts/central/v1
Marshalling error for key 'flately:cms/en-GB/districts/central/v1': CMS::District can't be referred to
You are trying to cache a Ruby object which cannot be serialized to memcached.

.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/dalli-2.7.6/lib/dalli/server.rb:414:in `dump'
```

Code

```
module CMS

  class District < ContentfulModel::Base

    CACHE_VERSION = :v1
    CONTENT_TYPE = :districts
    self.content_type_id = CONTENT_TYPE.to_s.singularize

    def self.cached_post(slug, locale = I18n.default_locale)
      Rails.cache.fetch([:cms, locale, CONTENT_TYPE, slug, CACHE_VERSION]) do
        find_by(slug: slug).load.first
      end
    end

  end

end
```

Result
```
=> #<CMS::District: @fields={:name=>"Central", :slug=>"central", :text=>"The central district consists of Soho, Lan Kwai Fong, mid-levels and the Central Harbour front area. Lan Kwai Fong and Soho are the premier nightlife destinations for many living in Hong Kong. Many expatriates also choose to settle within this area as this is also the big financial hub of Hong Kong with many large banks and financial institutions have set up office. \n\nBeing the financial hub of Hong Kong, you can expect the pricing for rent here to be higher than some of the other locations within Hong Kong. Once again, anything from studio flats closer to Lan Kwai Fong to more family oriented housing options located in the Mid levels area. \n", :backgroundColor=>"c2112e", :textColor=>"000000"} @sys={:space=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"92z8ivfvo55n"}>, :id=>"yWn2tcVSzmcsCWOQ6guWS", :type=>"Entry", :createdAt=>Sat, 18 Nov 2017 06:04:02 +0000, :updatedAt=>Thu, 11 Jan 2018 06:08:01 +0000, :revision=>6, :contentType=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"ContentType", :id=>"district"}>, :locale=>"en-GB"}>
```

Seems quite strange. This object from contentful looks pretty straight forward to me :)

## Gems

    contentful (0.12.0)
      http (~> 1.0)
      json (~> 1.8)
      multi_json (~> 1)
    contentful-management (1.10.0)
      http (> 1.0, < 3.0)
      json (~> 1.8)
      multi_json (~> 1)
    contentful_model (0.2.0)
      activesupport
      contentful (~> 0.9)
      contentful-management (~> 1.0)
      redcarpet
      require_all

**Comment by Frexuz** [comment]
Quick workaround:
`format.json { render json: districts.map(&:raw) }` but I'm not sure if that's a good idea, or if there are other ways :) ?

**Comment by Frexuz** [comment]
`.raw` also removes all nested `DynamicEntry` stuff. This is pretty much a show-stopper for me :(

```
posts[2]
#<CMS::Faq: @fields={:title=>"My listings", :slug=>"my-listings", :questions=>[#<Contentful::DynamicEntry[faq]: @fields={:title=>"Are listing fees renewed automatically?", :answer=>"Flately's listing fees are renewed automatically every 30 days. If the listing expires, than it will be barred from showing up in search results until it is renewed automatically. ", :category=>[#<CMS::Faq: @fields={:title=>"Payments", :slug=>"payments", :questions=>[#<Contentful::DynamicEntry[faq]: @fields={...} @sys={:space=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"Space", :id=>"92z8ivfvo55n"}>, :id=>"79AI2UwfZeAsqM4muOc08C", :type=>"Entry", :createdAt=>Tue, 23 Jan 2018 10:35:06 +0000, :updatedAt=>Mon, 05 Feb 2018 04:53:06 +0000, :revision=>2, :contentType=>#<Contentful::Link: @sys={:type=>"Link", :linkType=>"ContentType", :id=>"faq"}>, :locale=>"en-GB"}>, #<Contentful::DynamicEntry[faq]: @fields={:title=>"How much does it
```

```
posts[2].raw
{"sys"=>{"space"=>{"sys"=>{"type"=>"Link", "linkType"=>"Space", "id"=>"92z8ivfvo55n"}}, "id"=>"62bIQZxm0giCyMw2wwUy6E", "type"=>"Entry", "createdAt"=>"2018-01-19T07:31:55.801Z", "updatedAt"=>"2018-02-05T05:35:13.882Z", "revision"=>4, "contentType"=>{"sys"=>{"type"=>"Link", "linkType"=>"ContentType", "id"=>"category"}}, "locale"=>"en-GB"}, "fields"=>{"title"=>"My listings", "slug"=>"my-listings", "questions"=>[{"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"79AI2UwfZeAsqM4muOc08C"}}, {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"1ztaqQSjfisGq0EuYSS4GW"}}, {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"3ugy0BnqcEoggGMWOUaEsm"}}, {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"FOeauhtxeKsE6MSe8AYWC"}}, {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"691OHRWen6KgqsQ86A0yKG"}}, {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"lpWDlCLsJwAgiEWaImEYc"}}]}}
```

**Comment by dlitvakb** [comment]
Hey @Frexuz,

The `0.x` version of the CDA SDK is not serializable.

Please update to a newer release, `1.x` (works with `contentful_model 0.2.0`) and `2.x` (works with current `master`) are properly serializable.

Cheers

**Comment by Frexuz** [comment]
Not sure what's going on here :)

When im installing or updating contentful_mode, i get these versions

```

    contentful (0.12.0)
      http (~> 1.0)
      json (~> 1.8)
      multi_json (~> 1)
    contentful-management (1.10.1)
      http (> 1.0, < 3.0)
      json (~> 1.8)
      multi_json (~> 1)
    contentful_model (0.2.0)
      activesupport
      contentful (~> 0.9)
      contentful-management (~> 1.0)
      redcarpet
      require_all
```

So I can't update to `1.x` because of `~> 0.9`

So i tried `master`, but then I get this error on boot.

```
/Users/kristiangerardsson/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require /Users/kristiangerardsson/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/contentful_model-1955dd5d4388/lib/contentful_model/base.rb (uninitialized constant ContentfulModel::ChainableQueries). Please require the necessary files (RequireAll::LoadError)
```

**Comment by dlitvakb** [comment]
Hi @Frexuz,

Please add `gem 'require_all', '~> 1.0'` to your Gemfile.

This dependency will be removed in the next release. Which I'm expecting to release within April, as I'm starting active development again in this gem next week.

Cheers

**Comment by dlitvakb** [comment]
Current `master` has `require_all` removed.

Release of `1.0.0` version is scheduled for May 2nd.

Cheers
