### ISSUE TITLE
ContentfulModel gem incorrectly uses Object.const_get

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful_model#91]
In regards to the closed issue #30:
This is definitely still a problem if you have a class in a module, such as:

```
module A
   class B
   end
end
```

And then you try to get the constant for it using the way the ContentfulModel gem is doing:

```
Object.const_get(A::B.to_s.to_sym)
```

The error is:

```
NameError: wrong constant name A::B
```

This is because `.to_sym` makes a symbol containing the whole string including the `::`. Ruby does not expect this. `Object.const_get` expects you to pass a regular string if you need to reference module names. The following works:

```
Object.const_get(A::B.to_s)
```

And this is what the ContentfulModel gem should do.

Here's the whole testcase:
```
module A
   class B
   end
end

puts "works:"
puts Object.const_get(A::B.to_s).name

puts "fails:"
puts Object.const_get(A::B.to_s.to_sym).name
```

Here's the output on Ruby 2.4.0p0:

```
$ ruby test.rb
works:
A::B
fails:
test.rb:10:in `const_get': wrong constant name A::B (NameError)
        from test.rb:10:in `<main>'
```

**Comment by rezonant** [comment]
Actually this is for the 0.1.x branch, 0.2.x already has a fix, but it has dependency issues, which I will file in a new issue.
