### ISSUE TITLE
(uninitialized constant ContentfulModel::ChainableQueries). Please require the necessary files (RequireAll::LoadError)

### ISSUE THREAD

**Issue by joevandyk** [contentful/contentful_model#95]
```
$ ruby -v
ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin17]

$ cat Gemfile
source 'https://rubygems.org'
gem 'contentful_model'

$ bundle show
Gems included by the bundle:
  * activesupport (5.1.5)
  * addressable (2.5.2)
  * bundler (1.16.1)
  * concurrent-ruby (1.0.5)
  * contentful (0.12.0)
  * contentful-management (1.10.1)
  * contentful_model (0.2.0)
  * domain_name (0.5.20170404)
  * http (1.0.4)
  * http-cookie (1.0.3)
  * http-form_data (1.0.3)
  * http_parser.rb (0.6.0)
  * i18n (0.9.5)
  * json (1.8.6)
  * minitest (5.11.3)
  * multi_json (1.13.1)
  * public_suffix (3.0.2)
  * redcarpet (3.4.0)
  * require_all (2.0.0)
  * thread_safe (0.3.6)
  * tzinfo (1.2.5)
  * unf (0.1.4)
  * unf_ext (0.0.7.5)

$ cat test.rb
require 'contentful_model'

$ bundle exec ruby test.rb
/Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:102:in `rescue in block in require_all': Could not require /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/contentful_model-0.2.0/lib/contentful_model/base.rb (uninitialized constant ContentfulModel::ChainableQueries). Please require the necessary files (RequireAll::LoadError)
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:97:in `block in require_all'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `each'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:96:in `require_all'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:118:in `block in require_rel'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:117:in `each'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/require_all-2.0.0/lib/require_all.rb:117:in `require_rel'
	from /Users/joe/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/contentful_model-0.2.0/lib/contentful_model.rb:4:in `<top (required)>'
	from test.rb:1:in `require'
	from test.rb:1:in `<main>'

```

**Comment by joevandyk** [comment]
It looks like base.rb gets loaded before the file that defines `ChainableQueries` gets loaded?

**Comment by joevandyk** [comment]
It works if I downgrade the `require_all` gem to 1.5.0.

**Comment by joevandyk** [comment]
https://github.com/contentful/contentful_model/pull/96 probably fixes

**Comment by raybradley** [comment]
@joevandyk yes that's exactly what's happening and, yes, downgrading require_all resolves it. I'll rename the ticket per your suggestion.

**Comment by joevandyk** [comment]
https://github.com/contentful/contentful_model/pull/97 shows that tests are failing on latest master.

**Comment by rezonant** [comment]
The gemspec should explicitly depend on 1.5.0 until work can be done to make it work with `require_all` 2.0.

**Comment by joevandyk** [comment]
https://github.com/contentful/contentful_model/pull/96/files fixes it. @dlitvakb can that get merged and released?

**Comment by dlitvakb** [comment]
Hi there,

If possible, lock the version in your local `Gemfile` (this works unless you have other conflicting gems).

Within the next 2 weeks, work on `1.0.0` will be restarted and the `require_all` dependency will be completely removed.

Cheers

**Comment by joevandyk** [comment]
@dlitvakb Not releasing a fix means that version 0.2 is broken for just about everyone until they come to this issue and learn that they have to add another (non-obvious) line to their Gemfile. 

I think it would be worthwhile to release a new version of contentful_model that works on a new application.

**Comment by dlitvakb** [comment]
Hey @joevandyk,

I can do the merge, but cannot make a release, I'm currently on vacation and away from a computer. If just merging and then using `master` works for you, that would be ideal.

Also, making a `0.2.1` release currently is non-trivial, as there are a lot of minor (but still) breaking changes, and I'd spend a lot of time figuring out what should or should not be cherry-picked.

Cheers

**Comment by dlitvakb** [comment]
Hey everybody,

I am currently focusing on fixing the remaining bugs and adding the last few new features I want to have for the 1.0.0 release.

This means, I just removed the `require_all` dependency, so you can now update to the latest master version and this will no longer be an issue.

Cheers
